### ISSUE TITLE
Missing System UUID? Required for some software to track....

### ISSUE THREAD

**Issue by frankk74** [system76/coreboot#99] opened 2022-02-22 21:41 UTC
Seems that there isn't a system uuid assigned by coreboot or by system76's build of it: or just specifically for oryp7?

...
07/20/2021 4.13 coreboot 2021-07-20_93c2809

From dmidecode:

Handle 0x0001, DMI type 1, 27 bytes
System Information
	Manufacturer: System76
	Product Name: Oryx Pro
	Version: oryp7
	Serial Number: 123456789
	UUID: Not Settable
	Wake-up Type: Reserved
	SKU Number: Not Specified
	Family: Not Specified

From working install of same Popos release:

Handle 0x0001, DMI type 1, 27 bytes
System Information
	Manufacturer: Dell Inc.
	Product Name: OptiPlex 9020M
	Version: 00
	Serial Number: ZZZZZZ
	UUID: 4c4c4544-AAAA-ZZZZ-XXXX-b3c04f323832
	Wake-up Type: Power Switch
	SKU Number: 0669
	Family: Not Specified
...

Removed identifiers....

This might or might not be a related issue:

https://github.com/acidanthera/bugtracker/issues/711

OS: 

...
# pop-upgrade release check
checking if pop-upgrade requires an update
      Current Release: 21.10
         Next Release: 22.04
New Release Available: false
``

**Comment by crawfxrd** [comment] 2022-02-22 21:45
Duplicate of system76/firmware-open#268.

**Closed by crawfxrd** 2022-02-22 21:45 UTC
